services:
  db:
    image: postgres:16
    # ...unchanged...

  backend:
    build: ./backend
    working_dir: /code               # <— add this line
    environment:
      PYTHONPATH: /code              # <— keep this
      DATABASE_URL: postgresql+psycopg://app:app@db:5432/app
      SEED_ON_START: "true"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
